# Generated by Django 5.0.6 on 2024-06-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='created_at',
            new_name='upload_time',
        ),
    ]
