# Generated by Django 5.0.6 on 2024-07-10 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsam_app', '0002_rename_created_at_uploadedimage_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='folder_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
